project:
  type: book

book:
  title: "Interpreting and Visualizing Nested Models in 3D"
  author: "Ella Foster-Molina"
  chapters:
    - index.qmd
    - visualize_models_3d.qmd
    - joint_change.qmd
    - standard_error_in_gamma_direction.qmd

bibliography: references.bib

format:
  html:
    include-in-header: mathjax.html
    theme:
      - cosmo
      - brand

number-depth: 2

