project:
  type: book

book:
  title: "Interpreting and Visualizing Nested Models in 3D"
  author: "Ella Foster-Molina"
  chapters:
    - index.qmd
    - visualize_models_3d.qmd
    - interpret_joint_change_stderrors.qmd

bibliography: references.bib

format:
  html:
    include-in-header: mathjax.html
    theme:
      - cosmo
      - brand



